# Generated by Django 4.1.1 on 2022-12-23 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='solved',
            table='solved',
        ),
    ]
