# Generated by Django 4.1.1 on 2022-12-23 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstat', '0002_alter_solved_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='solved',
            table=None,
        ),
    ]
